# Generated by Django 4.1.2 on 2022-12-12 15:56

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_name_alter_account_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=Account.models.get_default_profile_image, max_length=255, null=True, upload_to=''),
        ),
    ]
